apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebanking
  labels:
    app: homebanking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebanking
  template:
    metadata:
      labels:
        app: homebanking
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
